services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 3;
      mc alias set myminio http://minio:9000 minioadmin minioadmin;
      mc mb --ignore-existing myminio/mlflow;
      exit 0;
      "

  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.12.0
    depends_on:
      minio-init:
        condition: service_completed_successfully
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow_data:/mlflow
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    command: >
      bash -c "pip install boto3 --quiet &&
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:///mlflow/mlflow.db
      --default-artifact-root mlflow-artifacts:/
      --serve-artifacts
      --artifacts-destination s3://mlflow
      --allowed-hosts '*'
      --cors-allowed-origins '*'"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:5000', timeout=2)"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ml_service
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ml_service"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build:
      context: ./app
    depends_on:
      db:
        condition: service_healthy
      mlflow:
        condition: service_healthy
    ports:
      - "5001:8501"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ml_service
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/ml_service
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MLFLOW_EXPERIMENT_NAME: HARNet-LateFusion
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin

volumes:
  postgres_data:
